### ISSUE TITLE
Noms des élèves

### ISSUE THREAD

**Issue by edi9999** [edi9999/cours-dweb-iut-haguenau#1]
Pour pouvoir faire les corrections, j'ai besoin de vos noms/prénoms, à écrire en réponse dans cette "issue"

**Comment by qhaensler** [comment]
Quentin HAENSLER

**Comment by Pappum** [comment]
Alexis SMOUTS

**Comment by fwust** [comment]
Florian WUST

**Comment by tmos** [comment]
Tom Canac

**Comment by ZussyFranck** [comment]
Franck Zussy

**Comment by Joel-Mercier** [comment]
Joel Mercier

**Comment by HugoBeyer67** [comment]
Hugo Beyer

**Comment by qkerguelen** [comment]
Quentin KERGUÉLEN

**Comment by Franz9425** [comment]
François MANG

**Comment by antoine-waag** [comment]
Antoine WAAG

**Comment by edi9999** [comment]
Ceux qui connaissent déjà github et git, mettez le code du TP1 en ligne sur un repository nommé `tp1-javascripting`.

Il suffit d'aller sur https://github.com/new pour créer le repository, puis faire depuis votre répertoire de code : 

```
git init
```

puis en remplacement "edi9999" par votre nom d'utilisateur, et "cours-dweb-iut-haguenau" par "tp1-javascripting"

```
git remote add origin https://github.com/edi9999/cours-dweb-iut-haguenau.git
```

puis 

```
git add .
git commit -m "Premier commit"

git push origin master
```

Puis mettez un lien vers votre repository dans cette issue.

**Comment by fwust** [comment]
https://github.com/florianwust/tp1-javascripting

**Comment by Joel-Mercier** [comment]
https://github.com/Joel-Mercier/tp1-javascripting

**Comment by Pappum** [comment]
https://github.com/Pappum/tp1-javascripting

**Comment by antoine-waag** [comment]
https://github.com/waagou/tp1-javascripting

**Comment by tmos** [comment]
https://github.com/tmos/cours-dweb-iut-haguenau
avec chaque TP dans le dossier correspondant :+1:

**Comment by qhaensler** [comment]
https://github.com/qhaensler/tp1-javascripting

**Comment by edi9999** [comment]
Pour la deuxième partie du TP, faites 

```
npm install -g learnyounode
learnyounode
```

puis mettez les "solutions" dans le même repository git (dans un autre dossier, comme @tmos https://github.com/tmos/cours-dweb-iut-haguenau )

**Comment by qkerguelen** [comment]
https://github.com/qkerguelen/tp1-javascripting

**Comment by ZussyFranck** [comment]
https://github.com/ZussyFranck/tp1-javascripting

**Comment by edi9999** [comment]
@HugoBeyer67 @Franz9425  il manque vos liens vers vos repositories, appelez moi si vous avez besoin d'aide.

**Comment by Franz9425** [comment]
https://github.com/Franz9425/tp1_javascripting

**Comment by HugoBeyer67** [comment]
https://github.com/HugoBeyer67/tp1-javascripting

**Comment by edi9999** [comment]
Bonjour, 

L'un de vous a oublié sa clé USB dans la salle. Je l'ai ramené au secrétariat mmi au 3e étage du bâtiment A.

Bonne journée

**Comment by edi9999** [comment]
Il me manque le tien Quentin Kerguelen de tp es6

**Comment by edi9999** [comment]
Bonjour à tous, pour info, j'ai créé un meetup sur Vim et la ligne de commande, le premier meetup sera le jeudi 28 juillet.

Voici le lien http://www.meetup.com/Vim-Strasbourg/events/232371514/
