### ISSUE TITLE
Discussion

### ISSUE THREAD

**Issue by edi9999** [edi9999/cours-dweb-iut-haguenau#2]

**Comment by fwust** [comment]
https://github.com/florianwust/tp3-reactjs

**Comment by qhaensler** [comment]
https://github.com/qhaensler/dweb-front-tp1

**Comment by Pappum** [comment]
https://github.com/Pappum/tp-react

**Comment by Joel-Mercier** [comment]
https://github.com/Joel-Mercier/tp3-reactjs

**Comment by antoine-waag** [comment]
https://github.com/waagou/tp-react

**Comment by tmos** [comment]
https://github.com/tmos/cours-dweb-iut-haguenau

**Comment by HugoBeyer67** [comment]
https://github.com/HugoBeyer67/cours-dweb-iut-haguenau

**Comment by qkerguelen** [comment]
https://github.com/qkerguelen/learn_react

**Comment by ZussyFranck** [comment]
https://github.com/ZussyFranck/cd

**Comment by edi9999** [comment]
@Franz9425 il me manque ton TP, est ce que tu peux me l'envoyer d'ci 18h ?

**Comment by edi9999** [comment]
Pour ceux que ça intéresse,  il y a un workshop ce soir sur la stack MEAN, c'est assez orienté pour les débutants.

C'est à 19h à la plage digitale (près de l'ugc, station Winston Churchill)

Découvrez ce Meetup avec Strasbourg Node.js http://meetu.ps/2PYRkt

**Comment by Franz9425** [comment]
Voila voila, je suis partis un peu précipitament désolé -_-
https://github.com/Franz9425/TP_React

**Comment by edi9999** [comment]
Hello, je vous ai mis les liens vers le fork des démos de React que l'on a fait :

https://github.com/edi9999/cours-dweb-iut-haguenau#le%C3%A7ons

**Comment by edi9999** [comment]
Aussi, si vous avez encore du mal avec les bases, vous pouvez également regarder les vidéos (gratuites) sur React ici : https://laracasts.com/series/do-you-react
