### ISSUE TITLE
Choix des projets

### ISSUE THREAD

**Issue by edi9999** [edi9999/cours-dweb-iut-haguenau#3]
@florianwust @qhaensler @Pappum @Joel-Mercier @waagou @tmos @HugoBeyer67 @qkerguelen @ZussyFranck @Franz9425

Je vous demande de choisir vos projets pour d'ici le 9 Décembre.
Les projets 2048 et Game of Life sont déjà pris (merci de quand meme faire un "Pull Request pour ajouter les noms + pseudos)

Pour prendre un projet, merci de faire une "Pull Request" par équipe (maximum 2 personnes par équipe) en éditant le fichier https://github.com/edi9999/cours-dweb-iut-haguenau/blob/gh-pages/lessons/projets-react.md (Il suffit de cliquer sur le petit crayon en haut à droite sur cette page) en ajoutant vos noms d'utilisateurs + noms complets en dessous du titre du projet. Je validerai ensuite ces PR (Pull Request).

Si vous voulez faire un autre projet que ceux proposés, il faut faire une liste des différentes fonctionnalités que vous comptez faire et l'inclure dand votre PR (merci d'être force de proposition), que je validerai ensuite. Il faut à tout prix que votre projet utilise React, mais également qu'il y ait une partie serveur (par exemple, jeu en équipe sur plusieurs ordinateurs, ou sinon sauvegarde/chargement sur un serveur). Votre projet ne doit pas obligatoirement être un jeu. Vous pouvez également choisir de faire en plus une version en utilisant React-native , qui permet de faire des applications iOS/Android natives avec le moteur React. Nous allons probablement faire un TP sur React-native.

**Comment by edi9999** [comment]
@florianwust @qhaensler @Pappum @Joel-Mercier @waagou @tmos @HugoBeyer67 @qkerguelen @ZussyFranck @Franz9425 

Bonjour, je n'ai reçu aucune PR de votre part (il est expliqué comment faire au-dessus) pour la répartition des projets.

J'attribuerai les projets aux personnes qui n'auront pas fait ça d'ici demain soir.

**Comment by ZussyFranck** [comment]
https://github.com/ZussyFranck/gameReact

**Comment by edi9999** [comment]
Hello ,

je vais récupérer les changements des repositories suivants demain à 5h30 du matin, merci d'avoir pushé tous vos changement avant cela.

2048-React:
    origin  https://github.com/florianwust/2048-React.git (fetch)
    origin  https://github.com/florianwust/2048-React.git (push)

Memory:
    origin  https://github.com/Pappum/ProjetFE (fetch)
    origin  https://github.com/Pappum/ProjetFE (push)

Nuntius:
    origin  https://github.com/Joel-Mercier/Nuntius (fetch)
    origin  https://github.com/Joel-Mercier/Nuntius (push)

life:
    origin  git@github.com:HugoBeyer67/life.git (fetch)
    origin  git@github.com:HugoBeyer67/life.git (push)

seotools:
    origin  git@github.com:tmos/seotools.git (fetch)
    origin  git@github.com:tmos/seotools.git (push)

seotools_modules:
    origin  git@github.com:tmos/seotools_modules.git (fetch)
    origin  git@github.com:tmos/seotools_modules.git (push)

worms:
    origin  https://github.com/ZussyFranck/gameReact.git (fetch)
    origin  https://github.com/ZussyFranck/gameReact.git (push)

@florianwust @qhaensler @Pappum @Joel-Mercier @waagou @tmos @HugoBeyer67 @qkerguelen @ZussyFranck @Franz9425

**Comment by edi9999** [comment]
Pour Nuntius, faites svp en sorte que l'on puisse installer les dépendances avec un simple npm install, ca ne marche pas car votre json est malformé ...
